// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LeitorCBF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220306194354_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CasaDoCodigo.Models.Rodadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHoraJogo");

                    b.Property<string>("NomeTimeCasa")
                        .IsRequired();

                    b.Property<string>("NomeTimeVisitante")
                        .IsRequired();

                    b.Property<int>("PlacarTimeCasa");

                    b.Property<int>("PlacarTimeVisitante");

                    b.Property<int>("Rodada");

                    b.HasKey("Id");

                    b.ToTable("Rodadas");
                });
#pragma warning restore 612, 618
        }
    }
}
